# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main_tkinter.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('app_icon.ico', '.'),
        ('config.json', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'csgo2_translation',
        'core',
        'core.audio',
        'core.audio.multi',
        'core.audio.sounddevice',
        'core.audio.wasapi',
        'core.audio.wasapi_free',
        'core.audio.pyaudio_impl',
        'core.speech',
        'core.speech.recognizer',
        'core.translation',
        'core.translation.translator',
        'core.tts',
        'core.tts.engine',
        'ui',
        'ui.main_window',
        'ui.overlay',
        'ui.license_dialog',
        'ui.setup_wizard',
        'config',
        'config.manager',
        'license',
        'license.manager',
        'utils',
        'utils.helpers',
        'whisper',
        'whisper.model',
        'whisper.audio',
        'googletrans',
        'deep_translator',
        'deep_translator.google',
        'EasyNMT',
        'transformers',
        'transformers.models.marian',
        'transformers.models.marian.modeling_marian',
        'transformers.models.marian.tokenization_marian',
        'sentencepiece',
        'torch',
        'torch.nn',
        'torch.cuda',
        'pyttsx3',
        'gtts',
        'pyaudio',
        'sounddevice',
        'numpy',
        'scipy',
        'scipy.signal',
        'cryptography',
        'psutil',
        'ctypes',
        'ctypes.wintypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'matplotlib',
        'IPython',
        'jupyter',
        'pytest',
        'sphinx',
        'black',
        'yapf',
        'zmq',
        'fasttext',  # Not required for this project
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='GameVoiceTranslator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='app_icon.ico',
)

