"""Tips when you can hear headphones but the app shows RMS=0 (WASAPI loopback)."""
print("WASAPI loopback troubleshooting")
print("=" * 50)
print()
print("1. In the app Audio Settings, select your headphones/speakers")
print('   (name should include "WASAPI loopback").')
print("2. Click Start Capture before playing game or system audio.")
print("3. Confirm Windows volume is up and audio is playing on that output.")
print("4. Run: python scripts/check_wasapi_setup.py")
print("5. Run: python scripts/diagnose_audio_routing.py while audio plays.")
